# Odoo 15 from bitnami
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo-15-doodba
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ssaid/charts
    targetRevision: main
    path: bitnami/odoo
    helm:
      # releaseName: odoo-15-bitnami
      values: |
        # allowEmptyPassword: true
        service:
          type: ClusterIP
        image:
          registry: docker.io
          repository: eynes/eynes15
          tag: 1.2.178
        postgresql:
          enabled: false
        odooEmail: admin
        odooPassword: admin
        externalDatabase:
          host: postgresql-15.postgresql-15.svc.cluster.local
          user: odoo
          password: odoo
          port: 5432
          postgresqlPostgresUser: odoo
          postgresqlPostgresPassword: odoo
          database: doodba15
        extraEnvVars:
          - name: ODOO_DATABASE_FILTER
            value: "^doodba15$"
        ingress:
          enabled: true
          hostname: odoo-15-doodba.local
        #   tls: true
        #   annotations:
        #     cert-manager.io/cluster-issuer: letsencrypt # ClusterIssuer Must Be Available

        command: ['/bin/bash','-c']
        args: ['/opt/odoo/common/entrypoint; createdb $PGDATABASE || true; [[ $(psql -d $PGDATABASE -c "\dt"|wc -l) -eq 0 ]] && odoo -d $PGDATABASE -i base --stop-after-init|| echo "Skipping initialization..."; odoo']

        doodba: true
        withoutDemo: true
        listDb: false
        smtpSsl: false
        emailFrom: ""
        unaccent: false
        proxy_mode: true

        useBackup:
          enable: false
          legacy: false
          params:
            AWS_ACCESS_KEY_ID: xxx
            AWS_SECRET_ACCESS_KEY: xxx
            DBS_TO_INCLUDE: ^prod
            DST: boto3+s3://xxx/xxx/
            PASSPHRASE: xxx
            TZ: UTC
  destination:
    server: "https://kubernetes.default.svc"
    namespace: odoo-15-doodba
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
