# Odoo 15 from bitnami
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo-15-doodba
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ssaid/charts
    targetRevision: main
    path: bitnami/odoo
    helm:
      # releaseName: odoo-15-bitnami
      values: |
        # allowEmptyPassword: true
        service:
          type: ClusterIP
        image:
          tag: 15.0.20230910-debian-11-r19
        postgresql:
          enabled: false
        odooEmail: admin
        odooPassword: admin
        externalDatabase:
          host: postgresql-15.postgresql-15.svc.cluster.local
          user: odoo
          password: odoo
          port: 5432
          postgresqlPostgresUser: odoo
          postgresqlPostgresPassword: odoo
          database: doodba15
        extraEnvVars:
          - name: ODOO_DATABASE_FILTER
            value: "^doodba15$"
        ingress:
          enabled: true
          hostname: odoo-15-doodba.local
        #   tls: true
        #   annotations:
        #     cert-manager.io/cluster-issuer: letsencrypt # ClusterIssuer Must Be Available
  destination:
    server: "https://kubernetes.default.svc"
    namespace: odoo-15-doodba
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
