apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-15
  namespace: argocd
spec:
  project: default
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.11.1
    helm:
      releaseName: postgresql-15
      values: |
        global:
          postgresql:
            auth:
              password: odoo
                # existingSecret: postgresql-secret
                # postgresqlPasswordSecretKey: postgresql-password
              username: odoo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: postgresql-15
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
